site_name: DevOps Notes
site_url: https://depgod.github.io/
repo_url: https://github.com/depgod/depgod.github.io
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: slate
    primary: indigo
    accent: pink
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.action.edit
    - content.tooltips
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - search.share
    - search.suggest
    - navigation.expand
    - navigation.indexes
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

nav:
  - Home: 
    - Welcome: index.md
  - Documentation:
    - Overview: documentation/index.md
    - Markdown Guide: markdown_basics.md
    - Versioning Guide: versioning.md
    - Self-Hosting:
      - Overview: documentation/selfhosting/index.md
    - Kubernetes:
      - multipass-k8s-cluster.md
    - CI/CD:
      - Overview: documentation/cicd/index.md
    - Networking:
      - Overview: documentation/networking/index.md
    - Infrastructure:
      - Overview: documentation/infrastructure/index.md
    - Miscellaneous:
      - Overview: documentation/miscellaneous/index.md
  - About:
    - About Me: about.md
  - Contact:
    - Get in Touch: contact.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      lang: en
      separator: '[\s\-\.]+'
      min_search_length: 2
  - git-revision-date-localized
  - mermaid2

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/depgod
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/myuser
  analytics:
    provider: google
    property: UA-XXXXXXXXX-X
