site_name: DevOps Notes
site_url: https://depgod.github.io/
repo_url: https://github.com/depgod/depgod.github.io
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  font:
    text: JetBrains Mono
    code: JetBrains Mono
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: deep-orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep-orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - content.code.copy

extra_css:
  - stylesheets/extra.css

nav:
  - Documentation:
    - index.md
    - Contents: documentation/contents.md
    - Markdown Guide: markdown_basics.md
    - Versioning Guide: versioning.md
    - CI/CD:
      - Overview: documentation/cicd/index.md
      - GitHub Actions with SonarQube & Harbor: documentation/cicd/github-actions-sonarqube-docker.md
    - Infrastructure:
      - Overview: documentation/infrastructure/index.md
      - Ansible Guide: documentation/infrastructure/ansible-guide.md
    - Kubernetes:
      - Overview: documentation/index.md
      - Multipass Local Cluster: multipass-k8s-cluster.md
      - HA K3s Cluster: k3s-ha-cluster.md
      - ArgoCD Setup: argocd-setup.md
      - Kubectl Cheat Sheet: documentation/kubernetes/kubectl-cheat-sheet.md
      - K9s CLI Guide: documentation/kubernetes/k9s-guide.md
      - Kubernetes Networking: documentation/kubernetes/kubernetes-networking.md
    - Self-Hosting:
      - Overview: documentation/selfhosting/index.md
      - Why Self-Host?: documentation/selfhosting/why-selfhost.md
    - Linux: documentation/linux/index.md
    - Networking: documentation/networking/index.md
    - Miscellaneous: documentation/miscellaneous/index.md
  - About: about.md
  - Contact: contact.md

docs_dir: docs
use_directory_urls: true
strict: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
