site_name: DevOps Notes
site_url: https://depgod.github.io/
repo_url: https://github.com/depgod/depgod.github.io
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: slate
    primary: black
    accent: indigo
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - content.code.copy

extra_css:
  - stylesheets/extra.css

nav:
  - Documentation:
    - Overview: documentation/contents.md
    - Markdown Guide: markdown_basics.md
    - Versioning Guide: versioning.md
    - CI/CD:
      - Overview: documentation/cicd/index.md
      - GitHub Actions with SonarQube & Harbor: documentation/cicd/github-actions-sonarqube-docker.md
    - Infrastructure:
      - Overview: documentation/infrastructure/index.md
      - Ansible Guide: documentation/infrastructure/ansible-guide.md
    - Kubernetes:
      - Overview: documentation/index.md
      - Multipass Local Cluster: multipass-k8s-cluster.md
      - HA K3s Cluster: k3s-ha-cluster.md
      - ArgoCD Setup: argocd-setup.md
    - Self-Hosting:
      - Overview: documentation/selfhosting/index.md
    - Linux:
      - Overview: documentation/linux/index.md
    - Networking:
      - Overview: documentation/networking/index.md
    - Miscellaneous:
      - Overview: documentation/miscellaneous/index.md
  - About: about.md
  - Contact: contact.md

docs_dir: docs
use_directory_urls: true
strict: true

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
