site_name: DevOps Notes
site_url: https://depgod.github.io/
repo_url: https://github.com/depgod/depgod.github.io
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  palette:
    scheme: slate
    primary: indigo
    accent: pink
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.action.edit
    - content.tooltips

nav:
  - Home: index.md
  - Versioning: versioning.md
  - About:
      - Contributing: contributing.md
      - License: license.md

markdown_extensions:
  - toc:
      permalink: "#"
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji

plugins:
  - search
  - git-revision-date-localized
  - mermaid2

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/myuser
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/myuser
  analytics:
    provider: google
    property: UA-XXXXXXXXX-X

extra_css:
  - styles/custom.css

extra_javascript:
  - scripts/custom.js

