site_name: DevOps Notes
site_url: https://depgod.github.io/
repo_url: https://github.com/depgod/depgod.github.io
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: slate
    primary: indigo
    accent: pink
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.action.edit
    - content.tooltips
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - search.share
    - search.suggest
    - navigation.expand
    - navigation.indexes

nav:
  - Home: 
    - Welcome: index.md
  - Documentation:
    - Overview: documentation/index.md
    - Markdown Guide: markdown_basics.md
    - Versioning Guide: versioning.md
    - Self-Hosting:
      - Overview: documentation/selfhosting/index.md
    - Kubernetes:
      - Multipass Local Cluster: multipass-k8s-cluster.md
      - HA K3s Cluster: k3s-ha-cluster.md
      - ArgoCD Setup: argocd-setup.md
    - CI/CD:
      - Overview: documentation/cicd/index.md
      - GitHub Actions with SonarQube & Harbor: documentation/cicd/github-actions-sonarqube-docker.md
    - Networking:
      - Overview: documentation/networking/index.md
    - Infrastructure:
      - Overview: documentation/infrastructure/index.md
      - Ansible Guide: documentation/infrastructure/ansible-guide.md
    - Miscellaneous:
      - Overview: documentation/miscellaneous/index.md
  - About:
    - About Me: about.md
  - Contact:
    - Get in Touch: contact.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search:
      lang: en
      separator: '[\s\-\.]+'
      min_search_length: 2
  - git-revision-date-localized
  - mermaid2:
      version: 10.6.1

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/depgod
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/myuser
  analytics:
    provider: google
    property: UA-XXXXXXXXX-X

extra_css:
  - stylesheets/extra.css
